name = "deca"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
node_compat = true
node_version = "20.10.0"

pages_build_output_dir = ".next"

[site]
bucket = ".next/static"
entry-point = "."