name = "deca"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
node_compat = true

# Production environment variables
[env.production]
NODE_VERSION = "20"

# Development environment variables
[env.development]
NODE_VERSION = "20"

# Optional: Configure caching
[site]
bucket = ".next/static"
entry-point = "."
