name = "deca"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "20.10.0"

[build.buildOptions]
command = "npm run build"
environment = { NODE_VERSION = "20.10.0" }

[site]
pages_build_output_dir = ".next"