[build]
command = "npm run build"
node_version = "20.10.0"

[build.environment]
NODE_VERSION = "20.10.0"

[site]
bucket = ".next/static"
entry-point = "."

[[build.upload]]
type = "build"
dir = ".next"