export interface Datashape {
  area: string;
  indicator: string;
  text: string;
  category: (
    | "MANAGEMENT"
    | "MARKETING"
    | "FINANCE"
    | "HOSPITALITY"
    | "ENTREPRENEUR"
  )[];
}

export interface GroupedData {
  [key: string]: Datashape[];
}

// DECA Event Types
export interface DECAEvent {
  id: string; // Official DECA event code (e.g., "ASM")
  name: string; // Official event name
  category: (
    | "MANAGEMENT"
    | "MARKETING"
    | "FINANCE"
    | "HOSPITALITY"
    | "ENTREPRENEUR"
  );
  careerCluster: string; // Official DECA career cluster
  careerPathway: string; // Official career pathway
  description: string; // Event description
  prepTime: number; // Preparation time in minutes
  roleplayDuration: number; // Roleplay duration in minutes
}

// Official DECA Scenario Types
export interface DECAScenario {
  id: string;
  // Header Information
  eventCode: string;
  careerCluster: string;
  careerPathway: string;
  
  // Participant Instructions
  participantInstructions: string[];
  
  // 21st Century Skills (generated by AI)
  centurySkills: string[];
  
  // Performance Indicators (generated by AI)
  performanceIndicators: string[];
  
  // Event Situation
  eventSituation: {
    roleDescription: string;
    companyBackground: string;
    businessChallenge: string;
    taskDescription: string;
    presentationContext: string;
  };
  
  // Judge Information
  judgeInstructions: {
    roleCharacterization: string;
    questionsToAsk: string[];
    evaluationCriteria: string;
  };
  
  // Scoring Information
  scoringRubric: {
    performanceIndicators: ScoringCriteria[];
    centurySkills: ScoringCriteria[];
    overallImpression: ScoringCriteria;
  };
  
  createdAt: Date;
}

export interface ScoringCriteria {
  name: string;
  maxPoints: number;
  levels: {
    exceeds: { points: string; description: string };
    meets: { points: string; description: string };
    below: { points: string; description: string };
    little: { points: string; description: string };
  };
}

// Legacy interface for backward compatibility
export interface RoleplayScenario {
  id: string;
  category: (
    | "MANAGEMENT"
    | "MARKETING"
    | "FINANCE"
    | "HOSPITALITY"
    | "ENTREPRENEUR"
  );
  eventId?: string;
  eventName?: string;
  title: string;
  scenario: string;
  context: string;
  roleDescription: string;
  objectives: string[];
  performanceIndicators: string[];
  judgesNotes: string[];
  environmentDescription: string;
  createdAt: Date;
}

export interface RoleplayResponse {
  prompt: string;
  userResponse: string;
  timestamp: Date;
}

export interface RoleplaySession {
  id: string;
  scenarioId: string;
  userId: string;
  scenario: RoleplayScenario;
  responses: RoleplayResponse[];
  startedAt: Date;
  completedAt?: Date;
}

export interface RoleplayMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
}

// Video Recording and AI Grading Types
export interface TranscriptSegment {
  id: string;
  text: string;
  startTime: number; // in seconds
  endTime: number;   // in seconds
  speaker: 'participant' | 'judge';
}

export interface FeedbackItem {
  id: string;
  timestamp: number; // in seconds
  type: 'strength' | 'improvement';
  category: 'performance_indicator' | '21st_century_skill' | 'overall_impression';
  title: string;
  description: string;
  relatedIndicator?: string; // For PI-specific feedback
}

export interface AIGradingScores {
  performanceIndicators: Array<{
    indicator: string;
    score: number; // 0-14
    feedback: string;
    level: 'exceeds' | 'meets' | 'below' | 'little';
  }>;
  centurySkills: Array<{
    skill: string;
    score: number; // 0-6
    feedback: string;
    level: 'exceeds' | 'meets' | 'below' | 'little';
  }>;
  overallImpression: {
    score: number; // 0-6
    feedback: string;
    level: 'exceeds' | 'meets' | 'below' | 'little';
  };
  totalScore: number; // 0-100
  overallFeedback: {
    strengths: string[];
    areasForImprovement: string[];
    recommendations: string[];
  };
}

export interface VideoSession {
  id: string;
  userId: string;
  scenarioId: string;
  scenario: DECAScenario;
  videoUrl: string;
  videoDuration: number; // in seconds
  transcript: TranscriptSegment[];
  aiGrading: AIGradingScores;
  timestampedFeedback: FeedbackItem[];
  createdAt: Date;
  processedAt: Date;
  status: 'recording' | 'processing' | 'completed' | 'failed';
}

